### ISSUE TITLE
Please kindly help me with iPhone 4

### ISSUE THREAD

**Issue by darkman088** [Jman012/Toxicity#65]
Hello

I am getting REALLY desperate with an iPhone 4 that I have available.
I want to use it for secure communication but it is stuck with iOS 7 and
all the apps require 8!!!
I am using tox on PC and on the iPhone would be great as well, just
Antidote wants iOS 8 as well!!! Please tell me if it is possible to use
Toxicity and kindly provide installation instructions, as it is not on the
Appstore. As you obviously got it, I am an iPhone greenhorn :P
Thanks a lot!!!

**Comment by jamamp** [comment]
Sorry, Toxicity is unsupported as of currently. I wouldn't even know where to start to get actual Tox support working. You'll have to ask on the Antidote project.

**Comment by darkman088** [comment]
Thanks I will ask them
